Login activity
Hoosfive/MemeApp pull request #3
Opened 2020-04-14 11:42 UTC by Hoosfive

Есть некоторые недоработки, перечислю ниже;
1) На кнопке отсутствует ripple эффект с того момента, как использовал библиотеку для прогресс бара. До этого эффект срабатывал, но теперь, видимо, придётся либо править библиотеку, либо использовать другой вариант реализации анимации загрузки. Пока пофиксить не удалось.
2) На TextFielBoxes значок глаза (в строке пароля) выглядит тускнее, не как на макете, скорее всего из-за прозрачности фона самого бокса, если критично, то буду править.
3) Возможно стоило распределить некоторые функции класса Login-Activity по другим классом, а то выглядит как божественный объект. То же касается констант, их как-то слишком много, если это так, то определю их в отдельный класс.
Заранее благодарю за ревью)

2020-04-14 13:22 UTC, midery requested changes

2020-04-14 13:22 UTC, midery commented on app/src/main/java/ru/surf/memeapp/LoginActivity.kt
> +    /*private fun testPrefs()
Закомментированный код следует удалять перед Pull Request

2020-04-14 13:22 UTC, midery commented on app/src/main/java/ru/surf/memeapp/LoginActivity.kt
> +        private const val PASS_HELPER_TEXT = "Пароль должен содержать $MIN_PASS_LENGTH символов"
Подобные сообщения лучше хранить в strings.xml для того, чтобы потом было проще поддерживать и работать с локализацией.

2020-04-14 13:22 UTC, midery commented on app/src/main/java/ru/surf/memeapp/LoginActivity.kt
> +        private const val TEXT_PASS = 0x00000091
Лучше без шестнадцатеричного кода в репозитории, это очень плохо для читаемости) 

И советую здесь уж лучше использовать переменную inputType, которую ты использовал (`InputType.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD`), с пояснением, почему ты еще прибавил к ней единицу.

2020-04-14 13:22 UTC, midery commented on app/src/main/java/ru/surf/memeapp/LoginActivity.kt
> +        const val USERDATA_PREFERENCES = "UserData"
Сейчас все переменные для работы с префами хранятся в этой activity. Если тебе вдруг понадобится вытащить, например, вытащить из них userName, то придется дублировать все эти переменные на новом экране.
Советую вынести их все в отдельный класс для работы с sharedPrefs юзера. Можешь даже обернуть его так, что префы не будут торчать наружу, и он просто будет отдавать и класть в них нужные данные. Вроде того же репозитория из примеров.

2020-04-14 13:22 UTC, midery commented on app/src/main/java/ru/surf/memeapp/LoginActivity.kt
> +    {
В kotlin/java не применяется такое форматирование методов, скобку нужно оставлять на предыдущей строке.
Знаю, когда долго пишешь на c#/c++, к этому сложно привыкнуть) 
Ctrl + Alt + L в студии применяет к файлу автоформатирование, это должно помочь

2020-04-14 13:22 UTC, midery commented on app/src/main/java/ru/surf/memeapp/LoginActivity.kt
> +            passHelperTextVisible()
Нейминг у методов обычно должен начинаться с глагола, так как методы что-то "делают".
Здесь подошел бы setPassHelperTextVisibility()

2020-04-14 13:22 UTC, midery commented on app/src/main/java/ru/surf/memeapp/LoginActivity.kt
> +        Handler().postDelayed({
Это не очень хорошая идея. Лоадер должен отображаться все время, пока идет запрос. А сейчас загрузка всегда идет фиксированное время. Это, во-первых, не даст юзеру со слабым интернетом понять, почему ничего не происходит спустя полторы секунды после нажатия на кнопку. А во-вторых, приведет к крешу с nullPointerException, если запрос длится меньше 1.5 секунды, и ты переходишь на другой экран. Так что этот метод нужно поправить, и перенести hideLoading() в onFailure/onResponse коллбеки

2020-04-14 13:22 UTC, midery commented on app/src/main/java/ru/surf/memeapp/NetworkService.kt
> +        fun createInstance(): Retrofit {
Тут лучше использовать lazy-конструктор, чтобы не создавать ретрофит каждый раз. У нас один инстанс ретрофита используется на все приложение.

2020-04-14 13:22 UTC, midery commented on app/src/main/java/ru/surf/memeapp/AuthApi.kt
> +    fun postData(@Body auth: AuthBody): Call<ResponseBody>
У метода странноватое название. Он используется для логина, так почему бы и не назвать его `login`?

2020-04-14 13:22 UTC, midery commented on app/src/main/java/ru/surf/memeapp/LoginActivity.kt
> +            .create(AuthApi::class.java)
Это не очень хорошее решение. Создание AuthApi задействует рефлексию и вообще не производительное. Советую создать эту штуку один раз на все приложение, так же как и в случае с retrofit.

2020-04-14 13:22 UTC, midery commented on app/src/main/java/ru/surf/memeapp/LoginActivity.kt
> +       lateinit var userData : ResponseBody
Зачем нам здесь это поле? Его ведь вполне можно расположить в onResponse-коллбеке

2020-04-14 13:22 UTC, midery commented on app/src/main/java/ru/surf/memeapp/LoginActivity.kt
> +                    userData = response.body()!!
Здесь мы получим креш, если response.body() == null, либо у response любой код кроме 200.

2020-04-14 13:22 UTC, midery commented on app/src/main/java/ru/surf/memeapp/LoginActivity.kt
> +            .enqueue(object : Callback<ResponseBody> {
Я бы на твоем месте спрятал бы этот код в репозитории авторизации, как это было показано в первой лекции про архитектуру. 

Сейчас код активити выглядит раздутым, и выполняет сразу несколько ответственностей - и отображает данные, и валидирует, и ходит в сеть, и сохраняет данные в память девайса. Этого многовато для одного класса. 

Я бы предложил использовать упрощенный clean: 

* Под работу с данными выделить репозиторий (AuthRepository), в котором будет метод логина и сохранения данных юзера. 
* Под валидацию и прокидывание команд из View - завести ViewModel или Presenter. 
* Для отображения состояний использовать как и сейчас activity.

2020-04-14 13:22 UTC, midery commented on app/src/main/java/ru/surf/memeapp/LoginActivity.kt
> +        passLine.setOnFocusChangeListener { view: View, b: Boolean ->
Здесь, эти параметры view и b необязательные, так что вполне можно заменить их нижним подчеркиванием, и убрать типы.

2020-04-14 13:22 UTC, midery commented on app/src/main/java/ru/surf/memeapp/ResponseBody.kt
> +data class ResponseBody (
Советую назвать класс по-другому: когда в приложении появится второй запрос, это имя жуе нельзя будет трактовать однозначно.

2020-04-14 13:22 UTC, midery commented on app/src/main/res/values/attrs.xml
> +    <declare-styleable name="ButtonBarContainerTheme">
Уверен, что эти строки нужны?

2020-04-14 13:22 UTC, midery commented on loadingbutton/build.gradle
> +configurations.maybeCreate("default")
Не советую таким образом подключать либы к android, для этого следует использовать только gradle. Иначе размер репозитория очень раздуется.

2020-04-20 02:01 UTC, Hoosfive commented on app/src/main/java/ru/surf/memeapp/LoginActivity.kt
> +            .enqueue(object : Callback<ResponseBody> {
Пока сделал это частично. По ходу разработки изучу MVP получше и применю уже его на проекте полностью.

2020-04-20 02:09 UTC, Hoosfive commented on app/src/main/java/ru/surf/memeapp/LoginActivity.kt
> +        private const val TEXT_PASS = 0x00000091
Не знаю как пояснить прибавление единицы. Я как бы вижу, что тут как раз есть разница в единицу
![image](https://user-images.githubusercontent.com/34771855/79707232-6bae3000-82c4-11ea-8574-81504c7c7b38.png)
![image](https://user-images.githubusercontent.com/34771855/79707215-5cc77d80-82c4-11ea-9f70-8d6c22e91c58.png)
Но понятия не имею что объяснять, разве только "ну, с единицей работает"))

2020-04-20 13:47 UTC, midery requested changes

2020-04-20 13:47 UTC, midery commented on app/src/main/java/ru/surf/memeapp/LoginActivity.kt
> +        progressBar.visibility
По-моему, здесь не меняется progressBar.visibility)

2020-04-20 13:47 UTC, midery commented on app/src/main/java/ru/surf/memeapp/LoginActivity.kt
> +    private fun toggleLoading() {
Лучше все-таки сделать метод setLoading, и вызывать его с параметром isLoading(true/false). Потому что в андроиде ты можешь, если постараться, несколько раз нажать на кнопку, и в итоге после этого у тебя view перейдет в неопределенное состояние.
Так что лучше всегда явно указывать:
перед загрузкой: setLoading(true)
при получении данных: setLoading(false)
при получении ошибки: setLoading(false)

2020-04-20 13:47 UTC, midery commented on app/src/main/java/ru/surf/memeapp/UserInfo.kt
> +    fun serialize(): String {
Во-первых, не советую создавать здесь Gson, это довольно дорогая операция, и она будет аффектить время запуска приложения.
Gson должен быть всегда в одном инстансе, на все приложение.
Во-вторых, советую все-таки не лениться, а сохранить данные юзера вручную в префы, построчно) 
Иначе рискуешь оказаться в ситуации, когда у тебя обновляется приложение, и одно поле удаляется, или его имя изменилось, и юзер перестал парситься, хотя множество других полей неизменны.

2020-04-20 13:53 UTC, Hoosfive commented on app/src/main/java/ru/surf/memeapp/LoginActivity.kt
> +        progressBar.visibility
Меняется же, работает)

2020-04-22 10:44 UTC, midery approved these changes

2020-04-23 22:50 UTC, merged